### ISSUE TITLE
WNDR4300 installation question

### ISSUE THREAD

**Issue by ddqp** [kissg1988/seafile-openwrt#1]
Hi,
Can I just download your package from git or change the source link to https://downloads.openwrt.org/snapshots/trunk/ar71xx/nand/packages/, to install seafile server?
I don't know how to follow your instruction in section "how to use", so I can follow the section "Installation" with the above changes.

Thanks,
DDQP

**Comment by kissg1988** [comment]
Hi,

that depends on what release of OpenWrt you are running on your device.

The packages in the snapshots repo are for the development branch and therefore they cannot be used on the latest stable release of OpenWrt (Barrier Breaker, aka. 14.07). For that release, you'll need to build the packages yourself by following the steps in the section "How to use".

If you use a version built from the development branch, you can simply run the command below to have Seafile installed:

<code># opkg update && opkg install seafile-server</code>

Regards,
Gergely

**Comment by ddqp** [comment]
Hi Gergely,

Thanks for your reply, I am running the stable release version, 
OpenWrt Barrier Breaker 14.07 / LuCI 0.12 Branch (0.12+git-222cc9c)
3.10.49
I will try to build it myself, have never done it before. If there are any questions, can I come here to you ?

Thanks
DDQP

**Comment by kissg1988** [comment]
Don't worry it's easy, just follow the instructions in the readme file. The build environment will let you know if it misses some dependencies, you can install them using your distros package manager (apt, yum etc).

**Comment by ddqp** [comment]
Hi,
Finally, finally I complied it. First time for me!! But I got this problem, I do installed sqlite3!! No idea how to fix it.

## **\* Installation completed, running configuration script...

This script will guide you to config and setup your seafile server.
Make sure you have read seafile server manual at

```
    https://github.com/haiwen/seafile/wiki
```

## Press [ENTER] to continue

check python modules ...
checking sqlite3
Error: Python module "sqlite3" not found. Please install it first

**\* ERROR: Configuration failed. Please fix the issues if any and re-run the script using the command below:
**\* "/etc/init.d/seafile setup"

**\* NOTE: you need to create an admin account before using seafile.
**\* Please run "/etc/init.d/seafile create_admin" to do so.
Stopping seafile server
done
wError: Python module "sqlite3" not found. Please install it first                                                                                                 Collected errors:
- satisfy_dependencies_for: Cannot satisfy the following dependencies for python-sqlite3:
-      python-light *
- opkg_install_cmd: Cannot install package python-sqlite3.
- pkg_run_script: package "seafile-server" postinst script returned status 1.
- opkg_configure: seafile-server.postinst returned 1.

---

root@OpenWrt:~# opkg files python-sqlite3
Package python-sqlite3 (2.7.3-2) is installed on usb and has the following files:
/opt/usr/lib/python2.7/sqlite3/dbapi2.py
/opt/usr/lib/python2.7/sqlite3/dump.py
/opt/usr/lib/python2.7/sqlite3/test/types.py
/opt/usr/lib/python2.7/sqlite3/test/userfunctions.py
/opt/usr/lib/python2.7/sqlite3/test/hooks.py
/opt/usr/lib/python2.7/sqlite3/test/**init**.py
/opt/usr/lib/python2.7/sqlite3/test/dbapi.py
/opt/usr/lib/python2.7/lib-dynload/_sqlite3.so
/opt/usr/lib/python2.7/sqlite3/test/regression.py
/opt/usr/lib/python2.7/sqlite3/test/transactions.py
/opt/usr/lib/python2.7/sqlite3/test/factory.py
/opt/usr/lib/python2.7/sqlite3/__init__.py
/opt/usr/lib/python2.7/sqlite3/test/py25tests.py
/opt/usr/lib/python2.7/sqlite3/test/dump.py

**Comment by ddqp** [comment]
If I do create account, below errors:

root@OpenWrt:~# /mnt/sda1/packages/etc/init.d/seafile create_admin
/etc/rc.common: cd: line 138: can't cd to _IPKG_INSTROOT_/usr/share/seafile

**Comment by kissg1988** [comment]
Please note that if you use an external drive for the installation, you will need to specify the path to the external root directory for all commands issued during the installation, quoting from README.md:

> To make opkg aware of your custom package repository, append the lines below to /etc/opkg.conf on your router (change paths as appropriate):
> 
> dest ext /mnt/sda1/extroot
> 
> src/gz seafile file:///mnt/sda1/packages/seafile
> 
> If you want to install the packages to an external location other than the / (root) directory, issue the following commands on your router (set the value of IPKG_INSTROOT so that it points to the desired destination directory):
> 
> opkg install shadow-useradd bash libncurses sudo procps procps-pkill
> 
> IPKG_INSTROOT=/mnt/sda1/extroot opkg -d ext install seafile-server
> 
> IMPORTANT: packages listed in the first command must be installed to the default root directory, otherwise they won't function correctly!
1. Do you have "ext" declared in your /etc/opkg.conf file and it's pointing to the correct location (the path where packages are to be _installed_)?
2. Do you run opkg with the parameter "-d ext" and also set the variable IPKG_INSTROOT to point to the same path? Both are required for the installation script to be able to do its job properly.

On the other hand, installing the packages to external storage is not very well tested and therefore it may have some bugs, although I did have luck installing Seafile server to a USB stick before switching to the development build and it was working fine.

I'm going to install Barrier Breaker to a spare Raspberry Pi I have nearby, I'll let you know if I find something that could help you.

**Comment by ddqp** [comment]
Thanks for your reply, Gergely.
Actually, I follow the instruction, paid attention to what you mentioned.
I am going to reinstall it into root, wndr4300 should have enough space.

**Comment by ddqp** [comment]
I install everything into root. Looks like it works now. But, it can't create fold in my usb.

## This is your configuration

ccnet config:        use existing config in /usr/share/seafile/ccnet
seafile data dir:         /mnt/sda1/searfile
seafile port:             12001

## seafile fileserver port:  8082

Press ENTER if the config is right, or anything else to re-config

Generating seafile configuration...
Directory /mnt/sda1/searfile cannot be created.
Error: failed to init seafile configuration

---

If i leave the default folder /usr/share/seafile/seafile-data, then I get below error:

## This is your configuration

ccnet config:        use existing config in /usr/share/seafile/ccnet
seafile data dir:         /usr/share/seafile/seafile-data
seafile port:             12001

## seafile fileserver port:  8082

Press ENTER if the config is right, or anything else to re-config

Generating seafile configuration...
Done.
done

Now initializing seahub database, please wait...

Loading ccnet config from /usr/share/seafile/ccnet
Loading seafile config from /usr/share/seafile/seafile-data
Creating tables ...
Creating table django_content_type
Creating table django_session
Creating table registration_registrationprofile
Creating table captcha_captchastore
Creating table api2_token
Creating table api2_tokenv2
Creating table avatar_avatar
Creating table avatar_groupavatar
Creating table base_uuidobjidmap
Creating table base_filediscuss
Creating table base_filecontributors
Creating table base_userstarredfiles
Creating table base_dirfileslastmodifiedinfo
Creating table base_filelastmodifiedinfo
Creating table base_userenabledmodule
Creating table base_groupenabledmodule
Creating table base_userlastlogin
Creating table base_commandslastcheck
Creating table base_innerpubmsg
Creating table base_innerpubmsgreply
Creating table base_devicetoken
Creating table contacts_contact
Creating table wiki_personalwiki
Creating table wiki_groupwiki
Creating table group_groupmessage
Creating table group_messagereply
Creating table group_messageattachment
Creating table group_publicgroup
Creating table message_usermessage
Creating table message_usermsglastcheck
Creating table message_usermsgattachment
Creating table notifications_notification
Creating table notifications_usernotification
Creating table options_useroptions
Creating table profile_profile
Creating table profile_detailedprofile
Creating table share_anonymousshare
Creating table share_fileshare
Creating table share_orgfileshare
Creating table share_uploadlinkshare
Creating table share_privatefiledirshare
Installing custom SQL ...
Installing indexes ...
SAXReaderNotAvailable: expat not supported
Error: Seahub syncdb failed

**Comment by kissg1988** [comment]
I believe you have a typo somewhere:

>  Directory /mnt/sda1/<strong>searfile</strong> cannot be created.

Anyway, I'm pretty sure that the built-in flash memory will not be sufficient to install Seafile and its dependencies. Although the WNDR4300 comes with 128 MB of flash, OpenWrt can only use about 16 MB as seen <a href="http://wiki.openwrt.org/toh/netgear/wndr4300#visual_representation1">here</a> because of the default flash layout. To change that, you would need to modify the layout which is something I wouldn't do without serial or JTAG access and knowledge on how to recover in case things go wrong.

My advice is to fetch a snapshot release of openwrt and install it on your router. This will have two advantages:
1. You'll be able to install Seafile through the package manager, no building required
2. You'll be able to use proper extroot functionality (ie. map the / path to an external storage drive)

I own a WNDR4300 router myself and Seafile is running perfectly on it using a similar setup (wndr4300 with USB HDD attached, running Bleeding Edge, r43753).

**Comment by kissg1988** [comment]
By the way, I've tried building the packages for my Raspberry but the build process failed at some point and I'm not sure how to proceed. Please consider my advice above. Thanks!

**Comment by ddqp** [comment]
I use a firmware with 128m flash enabled. So, after installation of seafile-server, I still got 40m left.

What a good chance! Can you share your openwrt-ar71xx-nand-wndr4300-ubi-factory.img and seafile installation file or firmware with seafil integrated? So I can simply flash the firmware. That would be much easier for me.

I am not a computer expert, actually I work on mechanic domain.

**Comment by kissg1988** [comment]
Sure, no problem, I'm going to build an image with Seafile integrated for you.

Have you used <a href="https://github.com/openwrt-mirror/openwrt/pull/3/files?diff=unified#diff-afca0f9db7fd7af7c8beccbc318c22de">this patch</a> to have the full flash space available?

I'm going to include it in the build for you.

**Comment by kissg1988** [comment]
I've successfully built the images for you (including the flash limitation patch mentioned above), you might download them using one of these links:

(links removed)

I think you can use the sysupgrade image since you already have openwrt running on your router and that way you can do the flashing without losing your current configuration.

IMPORTANT: Although the build completed successfully, I didn't have the chance to test the images as it seems openwrt might overwrite some "reserved" data at the end of the flash address space and I don't want to possibly lose the ability to switch back to the default factory image. Hope you understand.

Use the images _at your own risk_ and backup your configuration before flashing!

**Comment by ddqp** [comment]
Thank you very much, I really appreciate for your help. I will try this when I go back home (it's morning now). I will keep you updated.
Thanks,
DDQP

**Comment by ddqp** [comment]
I didn't build the firmware myself, it's from a local forum. But I think they discussed this patch. In addition, you don't need to worry about flash back to factory firmware, WNDR4300 is possible to be flash back and use tftp to flash back.

**Comment by ddqp** [comment]
I have tried, I tftp flash the img file, and when I use setup command, it give me below error. Router is fine to connect to internet.

root@OpenWrt:/# ./etc/init.d/seafile setup
sudo: unknown user: seafile
sudo: unable to initialize policy plugin

**Comment by kissg1988** [comment]
I believe you'll need to reinstall the package to have the user account 'seafile' created. Please try to run this command:

<code># opkg update && opkg install --force-reinstall seafile-server</code>

It seems post-install scripts don't run for integrated packages hence the missing user account.

**Comment by ddqp** [comment]
Here is what I dit:
1. vi etc/init.d/seafile
2. change all "seafile" to "root"
3. ./etc/init.d/seafile setup
4. ./etc/init.d/seafile start
5. ./etc/init.d/seafile create_admin
6. reboot router

I can sync photos or files from iphone or mac now, looks like it's the user name issue, but I don't know if it will cause any other issue? Do I need to go back and do what you said?

**Comment by ddqp** [comment]
anyway, I go back reinstall, now it's OK.

I can sync files now, but I can't download file uploaded by iphone from mac, no idea how to fix it.

**Comment by kissg1988** [comment]
Running seafile as root is a very bad idea. Should someone find a vulnerability in the code he/she would have full access to your router!

Please uninstall the packages, remove the directory /usr/share/seafile and reinstall. Hopefully that will fix your problems.

<code># opkg remove seafile-server seafile-ccnet seafile-seahub</code>
<code># rm -rf /usr/share/seafile</code>
<code># opkg install seafile-server</code>

Be careful, this might delete the files you have uploaded so far (depending on which directory you set as the data directory).

**Comment by ddqp** [comment]
pending on that, can't download file.

**Comment by ddqp** [comment]
anyway, thank you very much for your help.

**Comment by kissg1988** [comment]
I don't know why that happens, I use the desktop client on several Linux and Windows machines and they work like a charm, although I've never tried uploading stuffs from a smartphone.

However, your Seafile server seems to be up and running so your installation problem is solved now. :)

Please open an issue <a href="https://github.com/haiwen/seafile/issues">here</a> regarding the download problem. Thank you.

**Comment by ddqp** [comment]
Thank you for your help!

**Comment by ddqp** [comment]
Hi,
I finally fixed that problem, it should come from the libevhtp version, the firmware you compiled use the higher version, the one in your git is the 1.2.9-1, it works.

So I reflash back the my previous firmware and install the package built by my self and chmod -R 777 of my USB folder, now everything works like a milk!!

Again, thanks for your hard work on this project! I may promote your work in my community.

Thanks,
DDQP

**Comment by kissg1988** [comment]
Hi,

thanks for the update, I'll quote this in the issue you opened <a href="https://github.com/haiwen/seafile/issues/1191">here</a>.

Thanks,
Gergely
