### ISSUE TITLE
Seafile on extroot Chaos Calmer 15.05

### ISSUE THREAD

**Issue by nasahlpa** [kissg1988/seafile-openwrt#2]
Hi,

I sucessfully installed seafile on extroot on Chaos Calmer 15.05. Now on starting seafile in /mnt/daten/etc/init.d/seafile I get this message:

"/etc/rc.common: cd: line 143: can't cd to /usr/share/seafile"

I installed extroot (step 1 to 7) with this howto: https://wiki.openwrt.org/doc/howto/extroot.
Extroot is also defined in /etc/opkg.conf (dest ext /mnt/daten)
Any ideas?

Cheers

Edit: problem solved, when installing with extroot use opkg install ... instead of IPKG_INSTROOT=/mnt/sda1/extroot opkg -d ext install seafile-server

**Comment by kissg1988** [comment]
Hi,

as mentioned in the README, instructions are for Barrier Breaker only. Extroot functionality has changed a lot since the initial publishing of this port, so instructions might not work as expected with more recent releases.

**Comment by nasahlpa** [comment]
Hi,

thank you for your answer.

Your seafile port is also working on Chaos Calmer. After setting up 
the extroot seafile can be installed with opkg install seafile instead 
of IPKG_INSTROOT...

Thank you for your work, seafile is working great!

Cheers
